server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    
    # Định dạng các tệp mặc định
    index index.html index.htm;

    # GZip Optimization SEO/Speed
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

    location / {
        # Với Next.js Static Export, URL /about sẽ tương ứng file /about.html
        try_files $uri $uri.html $uri/ /index.html;
    }

    # Bắt lỗi chuẩn mực
    error_page 404 /404.html;
    location = /404.html {
        root /usr/share/nginx/html;
        internal;
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
